<?php
// +----------------------------------------------------------------------
// | CoreThink [ Simple Efficient Excellent ]
// +----------------------------------------------------------------------
// | Copyright (c) 2014 http://www.corethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: jry <598821125@qq.com> <http://www.corethink.cn>
// +----------------------------------------------------------------------
return array(
    'type'=>array(
        'title'=>'开启同步登录：',
        'type'=>'checkbox',
        'options'=>array(
            'Qq'=>'Qq',
            'Sina'=>'Sina',
            'Renren'=>'Renren',
            'Google'=>'Google',
        ),
    ),
    'meta'=>array(
        'title'=>'接口验证代码：',
        'type'=>'textarea',
        'value'=>'',
        'tip'=>'需要在Meta标签中写入验证信息时，拷贝代码到这里。'
    ),
    'group'=>array(
        'type'=>'group',
        'options'=>array(
            'Qq'=>array(
                'title'=>'QQ配置',
                'options'=>array(
                    'QqKEY'=>array(
                        'title'=>'QQ互联APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://connect.qq.com',
                    ),
                    'QqSecret'=>array(
                        'title'=>'QQ互联APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://connect.qq.com',
                    )
                ),
             ),
            'Sina'=>array(
                'title'=>'新浪配置',
                'options'=>array(
                    'SinaKEY'=>array(
                        'title'=>'新浪APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weibo.com/',
                    ),
                    'SinaSecret'=>array(
                        'title'=>'新浪APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weibo.com/',
                    )
                ),
            ),
            'Renren'=>array(
                'title'=>'人人配置',
                'options'=>array(
                    'RenrenKEY'=>array(
                        'title'=>'人人APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://dev.renren.com/',
                    ),
                    'RenrenSecret'=>array(
                        'title'=>'人人APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://dev.renren.com/',
                    )
                ),
            ),
            'Google'=>array(
                'title'=>'谷歌配置',
                'options'=>array(
                    'GoogleKEY'=>array(
                        'title'=>'谷歌APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：https://code.google.com/apis/console/',
                    ),
                    'GoogleSecret'=>array(
                        'title'=>'谷歌APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：https://code.google.com/apis/console/',
                    )
                )
            )
        )
    )
);
